### ISSUE TITLE
Update the current Marketplace flow to allow primary purchase, secondary purchase and shopping cart

### ISSUE THREAD

**Issue by luislucena16** [proyecto26/concertx-smartcontracts#13]
As part of the development of the ConcertX platform, we need to create a Smart Contract that allows musicians to create NFTs in a Marketplace where they can also raise funds that way with some emotional moment of their career or their LIVEs with their audience, the goal is that there are primary purchases, secondary purchases, shopping cart. We as ConcertX will charge a commission for both purchases.

### Definition of Done
The aim is to be able to test all the expected functionality, with purchases, commissions and cart within the Marketplace itself!

### Tasks
- [ ] The smart contract must allow for primary purchasing.
- [ ] The smart contract must allow for secondary purchasing
- [ ] The smart contract must allow you to buy different items from different collections and in different quantities (shopping cart).
- [ ] The smart contract must be available to set the ConcertX commission and what will go to the musician.
- [ ] It should be handled by tiers for premium versions
- [ ] Must allow to assign wallets with `onlyOwner` permissions with a focus on security
