### ISSUE TITLE
Chainlink VRF integration most current version

### ISSUE THREAD

**Issue by luislucena16** [proyecto26/concertx-smartcontracts#3]
As a user, I want to participate in drawings for tickets and prizes for different activities within the app.

**Definition of Done:**
- Functional code that based on its logic allows to make random draws through the decentralized oracle
- NFTs Raffle through the oracle
- Ticket raffle through the oracle
- Premium pass raffle through the oracle

**Tasks:**
- [ ] Implement Chainlink VRF with its most current version
- [ ] Test the implemented code with hardhat
- [ ] Verify usability with scripts
